// TODO(T7/M-34..M-36): TTP trait and safeguards implementation pending
//
// Mitigations from THREAT_MODEL.md:
// - M-05: Propose-only mode (default; ADR-0006)
// - M-15: LLM never triggers TTPs directly; only proposes
// - M-34: Each TTP declares default_rate_limit
// - M-36: Kill switch (Engagement.kill) accessible by hotkey
//
// See: docs/security/THREAT_MODEL.md §2.3, §2.5
// ADR: docs/adr/ADR-0012 (TTP trait)
// ADR: docs/adr/ADR-0006 (propose-only mode)

use serde::{Deserialize, Serialize};

/// TTP (Tactics, Techniques, and Procedures) trait.
///
/// All offensive actions must implement this trait to ensure
/// proper authorization flow (M-15: LLM proposes, human approves).
pub trait Ttp: Send + Sync {
    /// Human-readable TTP identifier (e.g., "nmap-syn-scan").
    fn id(&self) -> &str;

    /// Short description of what this TTP does.
    fn description(&self) -> &str;

    /// Check if this TTP requires human gate (M-36).
    ///
    /// Destructive TTPs (M-21 threats) must return `true`.
    fn requires_human_gate(&self) -> bool {
        false
    }

    /// Get rate limit configuration (M-34).
    fn rate_limits(&self) -> RateLimits {
        RateLimits::default()
    }

    /// Propose an execution plan (M-05, M-15).
    ///
    /// This is called in propose-only mode. Returns a plan
    /// that the operator must review and approve.
    ///
    /// # Errors
    /// Returns error if proposal generation fails.
    #[allow(clippy::todo)]
    fn propose(&self, _ctx: &ExecutionContext) -> Result<ExecutionPlan, crate::Error> {
        // TODO(T7/M-05): Implement proposal generation
        todo!("Ttp::propose not implemented (T7/M-05)")
    }

    /// Execute in dry-run mode (validation only, no network I/O).
    ///
    /// # Errors
    /// Returns error if validation fails.
    #[allow(clippy::todo)]
    fn execute_dry_run(&self, _plan: &ExecutionPlan) -> Result<DryRunOutput, crate::Error> {
        // TODO(T7/M-05): Implement dry-run validation
        todo!("Ttp::execute_dry_run not implemented (T7/M-05)")
    }

    /// Execute the TTP (only after human approval).
    ///
    /// This should only be called after propose-only gate is cleared.
    ///
    /// # Errors
    /// Returns error if execution fails or is rejected by scope validator.
    #[allow(clippy::todo)]
    fn execute(&self, _plan: &ExecutionPlan) -> Result<ExecutionResult, crate::Error> {
        // TODO(T7/M-02): Call scope validator before execution
        // TODO(T7/M-21): Log scope violations
        // TODO(T7/M-34): Apply rate limits
        todo!("Ttp::execute not implemented (T7)")
    }
}

/// Rate limit configuration for a TTP (M-34).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RateLimits {
    /// Maximum requests per second.
    pub max_rps: Option<u32>,
    /// Maximum concurrent requests.
    pub max_concurrent: Option<u32>,
}

impl Default for RateLimits {
    fn default() -> Self {
        Self {
            max_rps: Some(10),
            max_concurrent: Some(5),
        }
    }
}

/// Execution context for TTP proposals.
#[derive(Debug, Clone)]
pub struct ExecutionContext {
    /// Target address/hostname.
    pub target: String,
    /// Additional parameters.
    pub params: Vec<String>,
}

/// Execution plan generated by `propose()`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// TTP identifier.
    pub ttp_id: String,
    /// Target to be tested.
    pub target: String,
    /// Human-readable rationale.
    pub rationale: String,
    /// Estimated impact/risk level.
    pub risk_level: RiskLevel,
}

/// Risk level classification (M-21).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RiskLevel {
    /// Read-only, no state changes.
    Safe,
    /// May trigger IDS/IPS but no damage.
    Low,
    /// May cause service degradation.
    Medium,
    /// May cause service disruption (requires human gate).
    High,
}

/// Dry-run validation output.
#[derive(Debug, Clone)]
pub struct DryRunOutput {
    /// Whether the plan is valid.
    pub valid: bool,
    /// Validation messages.
    pub messages: Vec<String>,
}

/// Execution result.
#[derive(Debug, Clone)]
pub struct ExecutionResult {
    /// Whether execution succeeded.
    pub success: bool,
    /// Output data.
    pub output: Vec<u8>,
    /// Error message if any.
    pub error: Option<String>,
}

/// Enumeration of destructive TTP categories (M-21).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DestructiveTtp {
    /// Denial of Service.
    Dos,
    /// Data destruction.
    DataDestruction,
    /// Credential brute-force.
    CredentialBruteForce,
    /// Exploitation (code execution).
    Exploitation,
}

/// Check if a TTP requires human gate before execution (M-36).
#[must_use]
#[allow(clippy::todo)]
pub fn requires_human_gate(_ttp_id: &str) -> bool {
    // TODO(T7/M-21): Implement TTP risk classification
    // High-risk TTPs (DoS, exploitation) must return true
    todo!("requires_human_gate not implemented (T7/M-21)")
}
