"""Agent state definition for LangGraph orchestration.

This module defines the TypedDict schema used to pass state between
nodes in the LangGraph agent graph. The state is the single source
of truth for the current engagement iteration.
"""

from typing import Any, TypedDict


class AgentState(TypedDict):
    """State passed between agent nodes.

    Attributes:
        snapshot: Current graph state snapshot from Rust core.
        analysis: Reasoning output from the reason node.
        proposal: Action proposals generated by the plan node.
        decision: Approved actions ready for execution.
        iteration_count: Number of engagement loop iterations completed.
        history: List of previous iteration summaries.
        engagement_context: Scope, objective, and operator configuration.
    """

    snapshot: dict[str, Any]
    analysis: dict[str, Any]
    proposal: dict[str, Any]
    decision: dict[str, Any]
    iteration_count: int
    history: list[dict[str, Any]]
    engagement_context: dict[str, Any]
