"""LLM response parsing utilities.

Handles extraction of structured data from LLM responses, including:
- Stripping `<think>...</think>` tags from deepseek-r1 output (D-18)
- Extracting JSON from markdown code blocks or raw text
- Validating and constructing typed Proposal objects
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import Any


class ParseError(Exception):
    """Raised when LLM response cannot be parsed into expected structure."""


@dataclass(frozen=True, slots=True)
class Proposal:
    """Action proposal generated by the plan node.

    Compatible with future Rust Proposal struct (AGENT-04).

    Attributes:
        target: Target identifier (domain, IP, CIDR).
        ttp_id: MITRE ATT&CK technique ID (e.g., "T1590.001").
        params: TTP-specific parameters as key-value pairs.
        rationale: LLM's reasoning for this proposal.
    """

    target: str
    ttp_id: str
    params: dict[str, Any]
    rationale: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Proposal:
        """Construct Proposal from parsed JSON dict.

        Args:
            data: Dictionary with keys: target, ttp_id, params, rationale.

        Returns:
            Validated Proposal instance.

        Raises:
            ParseError: If required fields are missing or have wrong types.
        """
        required = ("target", "ttp_id", "params", "rationale")
        missing = [k for k in required if k not in data]
        if missing:
            raise ParseError(f"Missing required fields: {missing}")

        if not isinstance(data["target"], str):
            raise ParseError(f"target must be str, got {type(data['target']).__name__}")
        if not isinstance(data["ttp_id"], str):
            raise ParseError(f"ttp_id must be str, got {type(data['ttp_id']).__name__}")
        if not isinstance(data["params"], dict):
            raise ParseError(f"params must be dict, got {type(data['params']).__name__}")
        if not isinstance(data["rationale"], str):
            raise ParseError(f"rationale must be str, got {type(data['rationale']).__name__}")

        return cls(
            target=data["target"],
            ttp_id=data["ttp_id"],
            params=data["params"],
            rationale=data["rationale"],
        )


@dataclass(frozen=True, slots=True)
class Analysis:
    """Structured analysis from the reason node.

    Attributes:
        observations: Key observations about current state.
        gaps: Information gaps that need filling.
        priority_targets: Targets to focus on next.
        reasoning: LLM's chain of thought.
    """

    observations: list[str]
    gaps: list[str]
    priority_targets: list[str]
    reasoning: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Analysis:
        """Construct Analysis from parsed JSON dict.

        Args:
            data: Dictionary with keys: observations, gaps, priority_targets, reasoning.

        Returns:
            Validated Analysis instance.

        Raises:
            ParseError: If required fields are missing or have wrong types.
        """
        required = ("observations", "gaps", "priority_targets", "reasoning")
        missing = [k for k in required if k not in data]
        if missing:
            raise ParseError(f"Missing required fields: {missing}")

        if not isinstance(data["observations"], list):
            raise ParseError(
                f"observations must be list, got {type(data['observations']).__name__}"
            )
        if not isinstance(data["gaps"], list):
            raise ParseError(f"gaps must be list, got {type(data['gaps']).__name__}")
        if not isinstance(data["priority_targets"], list):
            raise ParseError(
                f"priority_targets must be list, got {type(data['priority_targets']).__name__}"
            )
        if not isinstance(data["reasoning"], str):
            raise ParseError(f"reasoning must be str, got {type(data['reasoning']).__name__}")

        return cls(
            observations=[str(o) for o in data["observations"]],
            gaps=[str(g) for g in data["gaps"]],
            priority_targets=[str(t) for t in data["priority_targets"]],
            reasoning=data["reasoning"],
        )


# Pattern to match <think>...</think> tags (case-insensitive, dotall)
_THINK_PATTERN = re.compile(r"<think>.*?</think>", re.IGNORECASE | re.DOTALL)

# Pattern to match JSON in markdown code blocks
_JSON_BLOCK_PATTERN = re.compile(r"```(?:json)?\s*\n?(.*?)\n?```", re.DOTALL)

# Pattern to match raw JSON object
_JSON_OBJECT_PATTERN = re.compile(r"\{.*\}", re.DOTALL)


def strip_think_tags(text: str) -> str:
    """Remove `<think>...</think>` tags from LLM response.

    The deepseek-r1 model (D-18) emits reasoning in these tags before
    the actual response. This function strips them to get clean output.

    Args:
        text: Raw LLM response text.

    Returns:
        Text with think tags and their contents removed, stripped.
    """
    return _THINK_PATTERN.sub("", text).strip()


def extract_json(text: str) -> dict[str, Any]:
    """Extract JSON object from LLM response text.

    Tries in order:
    1. JSON in markdown code block (```json ... ``` or ``` ... ```)
    2. Raw JSON object ({ ... })

    Args:
        text: Text potentially containing JSON.

    Returns:
        Parsed JSON as dictionary.

    Raises:
        ParseError: If no valid JSON found.
    """
    # First, strip think tags
    clean_text = strip_think_tags(text)

    # Try markdown code block first
    block_match = _JSON_BLOCK_PATTERN.search(clean_text)
    if block_match:
        try:
            parsed: dict[str, Any] = json.loads(block_match.group(1))
        except json.JSONDecodeError:
            pass  # Fall through to try raw JSON
        else:
            return parsed

    # Try raw JSON object
    obj_match = _JSON_OBJECT_PATTERN.search(clean_text)
    if obj_match:
        try:
            parsed = json.loads(obj_match.group(0))
        except json.JSONDecodeError as e:
            raise ParseError(f"Invalid JSON: {e}") from e
        else:
            return parsed

    raise ParseError("No JSON object found in response")


def parse_analysis(text: str) -> Analysis:
    """Parse LLM response into Analysis structure.

    Args:
        text: Raw LLM response from reason node.

    Returns:
        Validated Analysis instance.

    Raises:
        ParseError: If response cannot be parsed.
    """
    data = extract_json(text)
    return Analysis.from_dict(data)


def parse_proposal(text: str) -> Proposal:
    """Parse LLM response into Proposal structure.

    Args:
        text: Raw LLM response from plan node.

    Returns:
        Validated Proposal instance.

    Raises:
        ParseError: If response cannot be parsed.
    """
    data = extract_json(text)
    return Proposal.from_dict(data)
